/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aipr;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;

public class App {

    public static void main(String[] args) throws IOException {
        OpenAiServe ai = new OpenAiServe();
        CExtractor.extractcimmit("/mnt/c/code/");
        Map<String, ArrayList<String>> map = CExtractor.cimmitMap;
//        for (String key : map.keySet()) {
//            for (String result: map.get(key)) {
//                ai.makeRequest(result);
//            }
//        }

        //ai.makeRequest(thisString);
        System.out.println(map.keySet());
        System.out.println(map.get("commit 59daef8d55de04b91434b39d4411a7939107645b").get(0).length());
        System.out.println(map.get("commit 59daef8d55de04b91434b39d4411a7939107645b").get(0));
        System.out.println("----------------------------------------------------------------------------------------------");
        ai.makeRequest(map.get("commit 59daef8d55de04b91434b39d4411a7939107645b").get(0));
    }
}
