/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aipr;

import java.io.IOException;

import java.util.ArrayList;
import java.util.Map;


public class App {


    public static void main(String[] args) throws IOException, InterruptedException {
        OpenAiServe ai = new OpenAiServe();
        CExtractor.extractcimmit("/mnt/c/code/");
        Map<String, ArrayList<String>> map = CExtractor.cimmitMap;
        for(String x: map.keySet()) {
            for(int i=0; i < map.get(x).size(); i++) {
                if (map.get(x).get(i).contains("initial commit")) {
                    continue;
                }
                System.out.println(x);
                ai.makeRequest(map.get(x).get(i));
                //TimeUnit.SECONDS.sleep(3);
            }

        }
        System.out.println("Success, all changes have been commented, Have a nice day.");

    }
}
